-- 상품 테이블
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  category text,
  model_name text,
  min_monthly_fee numeric,
  contract text,
  management_type text,
  thumbnail text,
  description text,
  features jsonb default '[]'::jsonb,
  selling_points jsonb default '{}'::jsonb,
  active boolean default true,
  created_at timestamptz default now()
);

-- 상담 리드 테이블
create table if not exists public.leads (
  id text primary key,
  created_at timestamptz default now(),
  apartment_slug text,
  apartment_name text,
  name text,
  phone text,
  interest text,
  products jsonb default '[]'::jsonb,
  move_in_date text,
  message text,
  privacy_consent boolean,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  status text default 'NEW',
  source text
);

alter table public.products enable row level security;
alter table public.leads enable row level security;

create policy "public read products" on public.products for select using (true);
create policy "public insert leads" on public.leads for insert with check (true);
create policy "public read leads" on public.leads for select using (true);
