export const APARTMENTS = {
  '디에이치-방배': {
    slug: '디에이치-방배',
    name: '디에이치 방배',
    location: '서울특별시 서초구 방배동',
    households: '3064세대',
    moveInDate: '2026년 9월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '디에이치 방배\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/디에이치-방배-hero.jpg',
    recommendedProducts: [],
    campaign: '디에이치-방배',
    seoTitle: '디에이치 방배 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '디에이치 방배 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/디에이치-방배-og.jpg',
    phone: '1588-0000',
    brandColor: '#1f3b5c',
    brandAccent: '#7ba7d8',
    source: {"cafeName":"디에이치 방배 입주예정자협의회 공식카페","cafeUrl":"https://cafe.naver.com/dhbangbae","members":"약 1,200명","chat":"단지 입주민 오픈채팅방 운영 중","note":"방배5구역 재건축"},
  },
  '힐스테이트-메디알레': {
    slug: '힐스테이트-메디알레',
    name: '힐스테이트 메디알레',
    location: '서울특별시 은평구 대조동',
    households: '2451세대',
    moveInDate: '2026년 10월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '힐스테이트 메디알레\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/힐스테이트-메디알레-hero.jpg',
    recommendedProducts: [],
    campaign: '힐스테이트-메디알레',
    seoTitle: '힐스테이트 메디알레 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '힐스테이트 메디알레 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/힐스테이트-메디알레-og.jpg',
    phone: '1588-0000',
    brandColor: '#7a2e1a',
    brandAccent: '#d48c4a',
    source: {"cafeName":"힐스테이트 메디알레 입예협 공식카페","cafeUrl":"https://cafe.naver.com/hsmediale","members":"약 1,500명","chat":"동호수 인증 오픈채팅방 병행 운영","note":"대조1구역 재개발"},
  },
  '인덕원-퍼스비엘': {
    slug: '인덕원-퍼스비엘',
    name: '인덕원 퍼스비엘',
    location: '경기도 의왕시 내손동',
    households: '2180세대',
    moveInDate: '2026년 6월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '인덕원 퍼스비엘\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/인덕원-퍼스비엘-hero.jpg',
    recommendedProducts: [],
    campaign: '인덕원-퍼스비엘',
    seoTitle: '인덕원 퍼스비엘 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '인덕원 퍼스비엘 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/인덕원-퍼스비엘-og.jpg',
    phone: '1588-0000',
    brandColor: '#2a1f3b',
    brandAccent: '#b8a8d8',
    source: {"cafeName":"인덕원 퍼스비엘 입주예정자협의회","cafeUrl":"https://cafe.naver.com/persbiel","members":"약 1,400명","chat":"계약자 전용 카카오톡 오픈채팅방 운영","note":"내손라구역 재개발"},
  },
  '힐스테이트-회룡역': {
    slug: '힐스테이트-회룡역',
    name: '힐스테이트 회룡역 파크뷰',
    location: '경기도 의정부시 호원동',
    households: '1816세대',
    moveInDate: '2026년 4월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '힐스테이트 회룡역 파크뷰\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/힐스테이트-회룡역-hero.jpg',
    recommendedProducts: [],
    campaign: '힐스테이트-회룡역',
    seoTitle: '힐스테이트 회룡역 파크뷰 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '힐스테이트 회룡역 파크뷰 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/힐스테이트-회룡역-og.jpg',
    phone: '1588-0000',
    brandColor: '#7a2e1a',
    brandAccent: '#d48c4a',
    source: {"cafeName":"힐스테이트 회룡역 파크뷰 입예협","cafeUrl":"https://cafe.naver.com/hoheup","members":"약 850명","chat":"입주예정자 정보공유 오픈채팅방 운영","note":"호원동 재개발"},
  },
  '힐스테이트-평택화양': {
    slug: '힐스테이트-평택화양',
    name: '힐스테이트 평택화양',
    location: '경기도 평택시 화양지구 5BL',
    households: '1571세대',
    moveInDate: '2026년 3월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '힐스테이트 평택화양\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/힐스테이트-평택화양-hero.jpg',
    recommendedProducts: [],
    campaign: '힐스테이트-평택화양',
    seoTitle: '힐스테이트 평택화양 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '힐스테이트 평택화양 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/힐스테이트-평택화양-og.jpg',
    phone: '1588-0000',
    brandColor: '#7a2e1a',
    brandAccent: '#d48c4a',
    source: {"cafeName":"힐스테이트 평택화양 입주예정자 모임","cafeUrl":"https://cafe.naver.com/hspthwayang","members":"약 700명","chat":"계약자 인증 단톡방 운영","note":"화양지구 대단지"},
  },
  '인천-두산위브더센트럴': {
    slug: '인천-두산위브더센트럴',
    name: '인천 두산위브더센트럴',
    location: '인천광역시 동구 송림동',
    households: '1321세대',
    moveInDate: '2026년 1월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '인천 두산위브더센트럴\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/인천-두산위브더센트럴-hero.jpg',
    recommendedProducts: [],
    campaign: '인천-두산위브더센트럴',
    seoTitle: '인천 두산위브더센트럴 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '인천 두산위브더센트럴 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/인천-두산위브더센트럴-og.jpg',
    phone: '1588-0000',
    brandColor: '#3b4a3b',
    brandAccent: '#8aa7b8',
    source: {"cafeName":"인천 두산위브더센트럴 입예협 공식카페","cafeUrl":"https://cafe.naver.com/wevedercentral","members":"약 800명","chat":"입주민 소통 오픈채팅방 개설","note":"송림3구역 재개발"},
  },
  '지제역-반도체밸리': {
    slug: '지제역-반도체밸리',
    name: '지제역 반도체밸리 제일풍경채',
    location: '경기도 평택시 가재지구 2BL',
    households: '1152세대',
    moveInDate: '2026년 3월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '지제역 반도체밸리 제일풍경채\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/지제역-반도체밸리-hero.jpg',
    recommendedProducts: [],
    campaign: '지제역-반도체밸리',
    seoTitle: '지제역 반도체밸리 제일풍경채 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '지제역 반도체밸리 제일풍경채 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/지제역-반도체밸리-og.jpg',
    phone: '1588-0000',
    brandColor: '#3b2e1f',
    brandAccent: '#c4a88c',
    source: {"cafeName":"지제역 반도체밸리 제일풍경채 입예협","cafeUrl":"https://cafe.naver.com/jijepunggyeong","members":"약 650명","chat":"예비입주자 오픈채팅방 운영","note":"가재지구 도시개발"},
  },
  '두산위브더제니스-센트럴': {
    slug: '두산위브더제니스-센트럴',
    name: '두산위브더제니스 센트럴 원주',
    location: '강원특별자치도 원주시 명륜동',
    households: '1167세대',
    moveInDate: '2026년 3월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '두산위브더제니스 센트럴 원주\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/두산위브더제니스-센트럴-hero.jpg',
    recommendedProducts: [],
    campaign: '두산위브더제니스-센트럴',
    seoTitle: '두산위브더제니스 센트럴 원주 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '두산위브더제니스 센트럴 원주 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/두산위브더제니스-센트럴-og.jpg',
    phone: '1588-0000',
    brandColor: '#3b4a3b',
    brandAccent: '#8aa7b8',
    source: {"cafeName":"두산위브더제니스 센트럴 원주 입예협","cafeUrl":"https://cafe.naver.com/zenithwonju","members":"약 600명","chat":"사전점검 대비 단톡방 운영","note":"원동남산 재개발"},
  },
  '부산-에코델타시티': {
    slug: '부산-에코델타시티',
    name: '부산 에코델타시티 16BL 중흥S-클래스',
    location: '부산광역시 강서구 강동동',
    households: '1067세대',
    moveInDate: '2026년 11월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '부산 에코델타시티 16BL 중흥S-클래스\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/부산-에코델타시티-hero.jpg',
    recommendedProducts: [],
    campaign: '부산-에코델타시티',
    seoTitle: '부산 에코델타시티 16BL 중흥S-클래스 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '부산 에코델타시티 16BL 중흥S-클래스 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/부산-에코델타시티-og.jpg',
    phone: '1588-0000',
    brandColor: '#2e4a3b',
    brandAccent: '#8cc4a8',
    source: {"cafeName":"에코델타시티 중흥S-클래스 입주예정자 카페","cafeUrl":"https://cafe.naver.com/ecozunghung16","members":"약 550명","chat":"입주예정자 오픈채팅방 확인","note":"에코델타시티 공공택지"},
  },
  '힐스테이트-모종': {
    slug: '힐스테이트-모종',
    name: '힐스테이트 모종 블랑루체',
    location: '충청남도 아산시 모종동',
    households: '1060세대',
    moveInDate: '2026년 3월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '힐스테이트 모종 블랑루체\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/힐스테이트-모종-hero.jpg',
    recommendedProducts: [],
    campaign: '힐스테이트-모종',
    seoTitle: '힐스테이트 모종 블랑루체 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '힐스테이트 모종 블랑루체 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/힐스테이트-모종-og.jpg',
    phone: '1588-0000',
    brandColor: '#7a2e1a',
    brandAccent: '#d48c4a',
    source: {"cafeName":"힐스테이트 모종 블랑루체 입예협","cafeUrl":"https://cafe.naver.com/mojongblancruche","members":"약 500명","chat":"계약자 확인 단톡방 운영","note":"모종2지구"},
  },
  '검단신도시-호반써밋': {
    slug: '검단신도시-호반써밋',
    name: '검단신도시 호반써밋 (AB19)',
    location: '인천광역시 서구 불로동',
    households: '856세대',
    moveInDate: '2026년 3월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '검단신도시 호반써밋 (AB19)\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/검단신도시-호반써밋-hero.jpg',
    recommendedProducts: [],
    campaign: '검단신도시-호반써밋',
    seoTitle: '검단신도시 호반써밋 (AB19) 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '검단신도시 호반써밋 (AB19) 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/검단신도시-호반써밋-og.jpg',
    phone: '1588-0000',
    brandColor: '#1f3b4a',
    brandAccent: '#7bc4d8',
    source: {"cafeName":"검단 AB19 호반써밋 입예협 공식카페","cafeUrl":"https://cafe.naver.com/ab19hoban","members":"약 600명","chat":"호수공원역 인접 단톡방 운영","note":"검단신도시 3단계"},
  },
  '청량리-롯데캐슬': {
    slug: '청량리-롯데캐슬',
    name: '청량리 롯데캐슬 하이루체',
    location: '서울특별시 동대문구 청량리동',
    households: '761세대',
    moveInDate: '2026년 4월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '청량리 롯데캐슬 하이루체\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/청량리-롯데캐슬-hero.jpg',
    recommendedProducts: [],
    campaign: '청량리-롯데캐슬',
    seoTitle: '청량리 롯데캐슬 하이루체 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '청량리 롯데캐슬 하이루체 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/청량리-롯데캐슬-og.jpg',
    phone: '1588-0000',
    brandColor: '#5c1f1f',
    brandAccent: '#d8a07b',
    source: {"cafeName":"청량리 롯데캐슬 하이루체 입예협","cafeUrl":"https://cafe.naver.com/highluce7","members":"약 500명","chat":"사전점검 준비 오픈채팅방 개설","note":"청량리7구역 재개발"},
  },
  '영등포자이-디그니티': {
    slug: '영등포자이-디그니티',
    name: '영등포자이 디그니티',
    location: '서울특별시 영등포구 양평동1가',
    households: '707세대',
    moveInDate: '2026년 3월',
    heroBadge: '입주예정자 특별 상담',
    heroTitle: '영등포자이 디그니티\n입주 준비 렌탈 비교 상담',
    heroDescription: '정수기·비데·공기청정기·매트리스까지\n입주 전에 미리 비교하고 준비하세요.',
    heroImage: '/images/영등포자이-디그니티-hero.jpg',
    recommendedProducts: [],
    campaign: '영등포자이-디그니티',
    seoTitle: '영등포자이 디그니티 입주 렌탈 비교상담 | ALL렌탈',
    seoDescription: '영등포자이 디그니티 입주 예정자 렌탈 상담. 정수기·비데·공기청정기·매트리스 비교 상담 신청.',
    ogImage: '/images/영등포자이-디그니티-og.jpg',
    phone: '1588-0000',
    brandColor: '#1a3a2a',
    brandAccent: '#8cc49a',
    source: {"cafeName":"영등포자이 디그니티 입주예정자협의회","cafeUrl":"https://cafe.naver.com/ydpzaidignity","members":"약 480명","chat":"조합원/일반분양 오픈채팅방 분리 운영","note":"양평12구역 재개발"},
  },
}

export const DEFAULT_APARTMENT_SLUG = '디에이치-방배'
